【添加】qrcode package
RT-Thread-packages/qrcode pull request #1
Opened 2018-10-18 10:13 UTC by qgyhd1234

2018-10-18 10:13 UTC, qgyhd1234 commented
@armink

2018-10-18 10:44 UTC, armink requested changes
IAR 下也验证下吧

2018-10-18 10:44 UTC, armink commented on README.md
> +在 MSH 中输入命令 qrcode RT-Thread，可以在串口助手上打印出一个二维码来，利用手机扫码软件扫描后可以看到结果为 RT-Thread。
缺少了开启示例的介绍，另外可否把整个操作增加个 GIF 截图

2018-10-18 10:44 UTC, armink commented on README.md
> +            [*] Enable qrcode sample
示例默认关闭吧

2018-10-19 03:35 UTC, qgyhd1234 commented
@armink 已经测试iar，没问题

2018-10-19 06:25 UTC, merged